//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Heteroauxin.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Heteroauxin.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap action_Cancel_16xLG {
            get {
                object obj = ResourceManager.GetObject("action_Cancel_16xLG", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap action_minus_16xLG {
            get {
                object obj = ResourceManager.GetObject("action_minus_16xLG", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap folder_Closed_16xLG {
            get {
                object obj = ResourceManager.GetObject("folder_Closed_16xLG", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You need to select a variable on the left before you can add any values..
        /// </summary>
        internal static string FormMain_buttonDirectory_Choose_left {
            get {
                return ResourceManager.GetString("FormMain_buttonDirectory_Choose_left", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filter.
        /// </summary>
        internal static string FormMain_textBoxFilter_Enter_Filter {
            get {
                return ResourceManager.GetString("FormMain_textBoxFilter_Enter_Filter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap LightBulb_16xLG {
            get {
                object obj = ResourceManager.GetObject("LightBulb_16xLG", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have already add a new value. You cannot add more before you name it..
        /// </summary>
        internal static string MessageBox_Already_New {
            get {
                return ResourceManager.GetString("MessageBox_Already_New", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are about to apply all the environment variables to the system.This action cannot be undone. Any incorrect variables may cause problems to your system.Do you want to continue?.
        /// </summary>
        internal static string MessageBox_Apply_System {
            get {
                return ResourceManager.GetString("MessageBox_Apply_System", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are about to apply all the environment variables to the current user profile.This action cannot be undone. Any incorrect variables may cause problems to your system.Do you want to continue?.
        /// </summary>
        internal static string MessageBox_Apply_User {
            get {
                return ResourceManager.GetString("MessageBox_Apply_User", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Caution.
        /// </summary>
        internal static string MessageBox_Caution {
            get {
                return ResourceManager.GetString("MessageBox_Caution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you really want to delete this item?.
        /// </summary>
        internal static string MessageBox_Confirm_Delete {
            get {
                return ResourceManager.GetString("MessageBox_Confirm_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        internal static string MessageBox_Error {
            get {
                return ResourceManager.GetString("MessageBox_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to load environment variables from current user. Unfortunately, I do not know why this happends..
        /// </summary>
        internal static string MessageBox_Fail_Load_User {
            get {
                return ResourceManager.GetString("MessageBox_Fail_Load_User", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to apply changes to your system..
        /// </summary>
        internal static string MessageBox_Failed_Apply {
            get {
                return ResourceManager.GetString("MessageBox_Failed_Apply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to export environment variables to file!.
        /// </summary>
        internal static string MessageBox_Failed_Export {
            get {
                return ResourceManager.GetString("MessageBox_Failed_Export", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to load environment variables from file..
        /// </summary>
        internal static string MessageBox_Failed_Load_File {
            get {
                return ResourceManager.GetString("MessageBox_Failed_Load_File", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to load environment variables from system. Unfortunately, I do not know why this happends..
        /// </summary>
        internal static string MessageBox_Failed_Load_System {
            get {
                return ResourceManager.GetString("MessageBox_Failed_Load_System", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have not loaded environment variables yet..
        /// </summary>
        internal static string MessageBox_Not_Loaded {
            get {
                return ResourceManager.GetString("MessageBox_Not_Loaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The variables currently loaded is not for user. Do you want to apply them to the user?.
        /// </summary>
        internal static string MessageBox_Not_User {
            get {
                return ResourceManager.GetString("MessageBox_Not_User", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nothing to be saved..
        /// </summary>
        internal static string MessageBox_Nothing_Save {
            get {
                return ResourceManager.GetString("MessageBox_Nothing_Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have unsaved environment variables. Do you want to exit the program?.
        /// </summary>
        internal static string MessageBox_Unsaved_Exit {
            get {
                return ResourceManager.GetString("MessageBox_Unsaved_Exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have unsaved environment variables. Do you want to load new variables from file?.
        /// </summary>
        internal static string MessageBox_Unsaved_New {
            get {
                return ResourceManager.GetString("MessageBox_Unsaved_New", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have unsaved environment variables. Do you want to load the system environment variables?.
        /// </summary>
        internal static string MessageBox_Unsaved_System {
            get {
                return ResourceManager.GetString("MessageBox_Unsaved_System", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have unsaved environment variables. Do you want to load the user environment variables?.
        /// </summary>
        internal static string MessageBox_Unsaved_User {
            get {
                return ResourceManager.GetString("MessageBox_Unsaved_User", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning.
        /// </summary>
        internal static string MessageBox_Warning {
            get {
                return ResourceManager.GetString("MessageBox_Warning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Environment variables are successfully applied to the current user..
        /// </summary>
        internal static string StatusLabel_Apply_User_Successful {
            get {
                return ResourceManager.GetString("StatusLabel_Apply_User_Successful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Applying environment variables to current user..
        /// </summary>
        internal static string StatusLabel_Appying_User {
            get {
                return ResourceManager.GetString("StatusLabel_Appying_User", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All the values are valid directories..
        /// </summary>
        internal static string StatusLabel_Is_Valid {
            get {
                return ResourceManager.GetString("StatusLabel_Is_Valid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The highlighted values are not valid directories..
        /// </summary>
        internal static string StatusLabel_Not_Valid {
            get {
                return ResourceManager.GetString("StatusLabel_Not_Valid", resourceCulture);
            }
        }
    }
}
